In [5]:
# # : 주석, 코드실행을 무효화

# 3 + 2

In [6]:
# 1. 연산자 배우기
# 1-1 산술연산자

# '+', '-', '*', '/' : 사칙연산을 할 수 있는 것들.


In [7]:
a = 1
b = 5



In [8]:
a

1

In [9]:
# print() : 값 조회를 할 수 있는 함수

print(a)
print(b)

1
5


In [10]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

6
-4
5
0.2


In [13]:
# ** : 제곱
# // : 몫
# % : 나머지

print(2 ** 4)
print(17 // 3)
print(17 % 3)

16
5
2


In [14]:
print(2 ** 1.5)

2.8284271247461903


In [16]:
# 변수의 이름을 잘 지어주면 식별이 쉬워진다.
# 마트에서 우유, 초코렛, 사탕을 구매한다. 총 가격은 얼마일까?

# 곱하기와 덧셈, 뺄셈이 같이 있을때는 곱하기는 띄어쓰기를 안한다. (개취)
# 변수들의 라인을 맞추면 더 깔끔해진다.

mlik      = 2900
chocolate = 1000
candy     = 200

total_price = 1*mlik + 2*chocolate + 5*candy
print(total_price)

5900


In [20]:
# 지수표기법 적용 가능
# e : 10을 의미

print(3e6)   # 3 * (10 ** 6)
print(3e+6)
print(3e-2)

3000000.0
3000000.0
0.03


In [22]:
# n 진수 표현 가능

print(int("1001",2))
print(int("1001",3))

9
28


In [28]:
# 1-2 관계연산자
# '>', '>=', '==', '!='
# 관계연산자의 결과값은 bool로 나온다. (bool : True or False)

a = 3
b = 5

print(a > b)
print(a < b)
print()

print(3 > 3)
print(3 >= 3)
print('\n')

print(a == 3)
print(b != 3)

False
True

False
True


True
True


In [29]:
print(40 - 32 / 2 == 24)
print(40 - 32 / 2 == 4)

True
False


In [34]:
# 1-3 논리연산자
# and, or, not


print(True and True)
print(True and False)
print()

print(True or False)
print()

print(not True)
print(not False)

True
False

True

False
True


In [38]:
# ex) 성인이면서, 충남대학교 재학중인 학생만 맥주 500ml를 무료로! 나는 받을 수 있을까?

age = 21
school = "충남대학교"

print("나는 맥주를 받을 수 있나? :",age >= 20 and school == "충남대학교")

나는 맥주를 받을 수 있나? : True


In [40]:
# Data Type
# type() : 데이터 타입을 조회할 수 있는 함수

print(a)
print(type(a))

3
<class 'int'>


In [44]:
# 2-1 int : 정수형 자료
# 1, 2, 3, ... -1, -2


a, b = 4, 5
print(a, type(a))
print(b, type(b))

print(a + b, type(a + b))
print(a / b, type(a / b))

4 <class 'int'>
5 <class 'int'>
9 <class 'int'>
0.8 <class 'float'>


In [45]:
# 2-2 float : 실수형 자료

print(type(0.6))

<class 'float'>


In [46]:
c = 3.0
d = 3

print(type(c))
print(type(d))

<class 'float'>
<class 'int'>


In [48]:
# float를 int로 바꾸기

print(int(c), type(int(c)))

3 <class 'int'>


In [50]:
# int를 float로 바꾸기

print(float(d), type(float(d)))

3.0 <class 'float'>


In [52]:
# float를 int로 바꿀때에는 소수점이 짤린다. (내림)

int(3.7)

3

In [55]:
# complex : 복소수형 자료

3 +5j

print(type(3 + 5j))

<class 'complex'>


In [58]:
# 반올림표현 가능
# round(수, 자릿수)

print(round(1 / 7, 2))
print(round(1 / 7, 3))
print(round(1 / 7, 4))
print(round(1 / 7, 5))
print(round(1 / 7, 6))


0.14
0.143
0.1429
0.14286
0.142857


In [60]:
# 2-3 bool type과 None type

# bool : True, False
# None : 진짜 없는거.

print(type(True))

t = True
f = False

# True : 1에 해당, False : 0에 해당

print(int(t))
print(int(f))

<class 'bool'>
1
0


In [63]:
# None type : 'nan', "None"


print(float("nan")) # 컴퓨터가 수용할 수 있는 숫자의 한계치를 넘어설때 나옴
print(float("inf"))
print(float("-inf"))

nan
inf
-inf


In [64]:
# None

None

In [65]:
# 2-4 str : 문자형자료(string)
# 따옴표를 이용해서 변수에 입력해야한다.

school = "충남대학교"

type(school)

str

In [66]:
# 작은따옴표, 큰 따옴표 모두 사용 가능

print("충남대학교")
print('충남대학교')

충남대학교
충남대학교


In [67]:
# 혼용 불가능

print('충남대학교")

SyntaxError: ignored

In [69]:
# int나 float를 str로 변환가능

a = 5
print(str(a))
print(type(str(a)))

5
<class 'str'>


In [71]:
b = 5
c = str(6)

print(b, c)

# str와 int, float는 연산이 불가능
print(b + c)

5 6


TypeError: ignored

In [72]:
# str 끼리는 연산이 가능

p = "3"
q = "5"

print(p + q)

35


In [74]:
# str 끼리의 + 연산은 그냥 가져다 붙이기

aa = "아"
bb = "어"

aa + bb

'아어'

In [75]:
# 빼기는 불가능

p - q

TypeError: ignored

In [77]:
# * 연산도 가능

cc = "정신나갈거가태"

cc * 50

'정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태정신나갈거가태'

In [91]:
# 2-5 list형 자료
# 대괄호로 선언

A = [1, 2, 3, 4, 5]
type(A)

list

In [92]:
B = ['명수', '은우', 3, 6]
print(B)

['명수', '은우', 3, 6]


In [81]:
# list에는 곱하기 연산 가능
B * 3

['명수', '은우', 3, 6, '명수', '은우', 3, 6, '명수', '은우', 3, 6]

In [84]:
# list 안에 list 입력 가능

C = [A, B]
print(C)

[[1, 2, 3, 4, 5], ['명수', '은우', 3, 6]]


In [87]:
# list의 특징 : 순서가 있고, 수정가능한(mutable) 객체의 집합
# 수정가능이란? : 삭제, 추가, 원소 자체를 다른것으로 교체

# 내부 원소에 접근시 index를 이용하여 접근, 이것을 indexing이라 한다.
# 파이썬은 index가 0부터 시작한다.

print(A)
print(A[0])  # A list에 있는 '첫번째' 원소
print(A[2])  

[1, 2, 3, 4, 5]
1
3


In [88]:
# index의 범위를 벗어나면 오류
print(A[7])

IndexError: ignored

In [89]:
# 비어있는 list만들기

C = []
D = list()

print(C)
print(D)

[]
[]


In [93]:
# list끼리 연산 가능

A + B   # 합집합(Union)

[1, 2, 3, 4, 5, '명수', '은우', 3, 6]

In [94]:
# str을 list로 변환?

list(school)

['충', '남', '대', '학', '교']

In [95]:
# 이런식으로도 list작성이 가능하다.

E = ["사과", "바나나", "포도",
     "라면", "우동",
     "사이다", "콜라"]

print(E)

['사과', '바나나', '포도', '라면', '우동', '사이다', '콜라']


In [98]:
# list는 음수 indexing 가능

print(A)
print(A[-1]) # list의 끝에있는 원소
print(A[-2])

[1, 2, 3, 4, 5]
5
4


In [109]:
# 여러개의 indexing도 가능, 이것을 slicing 이라 한다.
# slicing은 콜론(":")을 이용해서 한다

F = [1,2,3,4,5,6,7,8,9,10]

print(F)
print(F[2:6])
print(F[0:-2])
print()

# 처음부터 n번째 까지
print(F[0:6])
print(F[:6])
print()

# n번째 부터 끝까지
print(F[4:])
print()

# n번씩 건너 뛰어서 (step)
print(F[::2])
print(F[::3])
print(F[::-2])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]

[5, 6, 7, 8, 9, 10]

[1, 3, 5, 7, 9]
[1, 4, 7, 10]
[10, 8, 6, 4, 2]


In [112]:
# 값 조회 가능

print(1 in A)
print(14 in A)

True
False


In [113]:
# list에 원소 추가 가능

# append : list 맨 마지막에 원소를 추가한다.
print(A)



[1, 2, 3, 4, 5]


In [114]:
A.append(7)
print(A)

[1, 2, 3, 4, 5, 7]


In [116]:
# insert : 원하는 자리에 원소를 추가 가능

A.insert(1, 10)


In [117]:
print(A)

[1, 10, 2, 3, 4, 5, 7]


In [118]:
# extend : 맨 마지막에 추가할 리스트 입력

A.extend(["가","나"])
print(A)

[1, 10, 2, 3, 4, 5, 7, '가', '나']


In [119]:
# 삭제가능
# del로 선언, index 번호로 입력.

del A[1]
print(A)

[1, 2, 3, 4, 5, 7, '가', '나']


In [120]:
# remove로 원소 직접 삭제 가능

A.remove("가")
print(A)

[1, 2, 3, 4, 5, 7, '나']


In [122]:
# 숫자 정렬 가능
# sort()로 정렬 (오름차순)

H = [1,7,3,4,8,2,10]
print(H)
print()

H.sort()
print(H)

[1, 7, 3, 4, 8, 2, 10]

[1, 2, 3, 4, 7, 8, 10]


In [123]:
# 내림차순으로 정렬 가능
H.sort(reverse = True)
print(H)

[10, 8, 7, 4, 3, 2, 1]


In [125]:
# range를 이용해서 수열을 생성 가능

range(1, 10)
list(range(1,10)) # 파이썬은 끝에것을 빼먹는다.

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [126]:
list(range(10)) # 시작은 0부터

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [128]:
# 등차수열 생성 가능

print(list(range(0,10,2)))
print(list(range(0,50,7)))

[0, 2, 4, 6, 8]
[0, 7, 14, 21, 28, 35, 42, 49]


In [130]:
# list의 길이(원소 몇개로 이뤄져있는지)는 len()을 이용하여 얻는다.

Q = list(range(20))
print(Q)

print(len(Q))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
20


In [132]:
QQ = ['가', '나', '다']
len(QQ)

3

In [134]:
# list 원소 수정
# list의 index를 이요해서 수정 가능

QQ[1] = '마'
print(QQ)

['가', '마', '다']


In [133]:
# 2-6 tuple형 자료
# list와 유사하지만 크기와 수정이 불가(immuatable)
# 소괄호로 선언


T = (1,6,4)
print(T)
print(type(T))

(1, 6, 4)
<class 'tuple'>


In [135]:
# 수정 불가능

T[1] = 20

TypeError: ignored

In [136]:
# 삭제 불가능

del T[1]

TypeError: ignored

In [138]:
# 2-7 사전(dictionary)형 자료

# key(immutable)와, value(mutable) 가 맵핑된 자료

# 선언형식 : 중괄호를 이용하여 선언
# {key : value}

AD = {"사과" : 2, "바나나" : 3}
print(AD)
print(type(AD))

{'사과': 2, '바나나': 3}
<class 'dict'>


In [139]:
# 수정을 할 때는 key값으로 접근하여 수정가능

AD['사과'] = 7
print(AD)

{'사과': 7, '바나나': 3}


In [140]:
# 3 Numpy 패키지실습

# Numpy : 선형대수 라이브러리
# 라이브러리? : 코드를 작성할 필요 없이 많은 동작을 수행할 수 있게 해주는 함수와 매서드

# 사용을 하려면 불러와야한다.

import numpy

In [144]:
print(numpy.sin(30))
print(numpy.sin(numpy.pi))
print(numpy.exp(1))   # 지수합수
print(numpy.sqrt(2))  # 루트

-0.9880316240928618
1.2246467991473532e-16
2.718281828459045
1.4142135623730951


In [145]:
# 라이브러리를 내가 원하는 문자로 불러올 수 있다.

import numpy as np

In [147]:
print(np.sin(30))
print(np.sin(np.pi))

-0.9880316240928618
1.2246467991473532e-16


In [149]:
# 벡터 생성 가능
# array형 자료


array1 = np.array([2,4,3,5])  # list를 array로 바꿔라
print(array1)
print(type(array1))

[2 4 3 5]
<class 'numpy.ndarray'>


In [150]:
array2 = np.array([3,5,4,5])

In [152]:
# array는 벡터형 자료이기 때문에 벡터연산이 가능

print([1,2,3,4] + [6,7,8,9])
print(array1 + array2)

[1, 2, 3, 4, 6, 7, 8, 9]
[ 5  9  7 10]


In [161]:
# array로 행렬입력 가능
# 대괄호 2개 필요

array3 = np.array([[1,2,3], [4,5,6], [7,8,10]])
array4 = np.array([[1,1,1], [2,2,2], [3,3,3]])

print(array3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [157]:
# 행렬곱 가능
II = np.array([[1,0,0], [0,1,0], [0,0,1]])
array3 * II   # * : 각 원소끼리의 곱 (pointwise 하게 곱하게 된다)

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [158]:
# np.matmul

np.matmul(array3, II)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
# 역행렬 계산
np.linalg.inv(array3)

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [ ]:
# 연습문제 1

banana = 